const ary = {
	sqDp:{//申请店铺的接口 
		id:'membertoshop/sqdp',
		name:'getSqdp'
	},
	myStoreList:{//一人多店铺列表
		id:'mystore/MyStoreList',
		name:'getMyStoreList'
	},
	mystore:{//我的店铺的管理信息	
		id:'mystore/mystore',
		name:'getMystore'
	},
	firstrunscores:{//申请预存的第一个接口 
		id:'store/firstrunscores',
		name:'getFirstrunscores'
	},      
	secondrunscores:{//申请预存的第二个接口
		id:'store/secondrunscores',
		name:'getSecondrunscores'
	},
	jionrunscores:{//申请预存的第三个接口  
		id:'store/jionrunscores',
		name:'getJionrunscores'
	}, 
	storeskewm:{//商家收款二维码
		id:'scores/storeskewm',
		name:'getStoreskewm'
	},					
	storexxjl:{//消费记录列表	（日份）
		id:'mystore/xstorexxjl',
		name:'getStorexxjl'
	},			
	mymember:{//我的会员	
		id:'mystore/mymember',
		name:'getMymember'
	},	
	myMsgList:{//短信群发的信息列表
		id:'mystore/StoreMessageLook',
		name:'get'
	},
	msgSend:{//短信群发	
		id:'mystore/StoreMessageSend',
		name:'getStoreMessageSend'
	},		
	storexfxq:{//账单详情	
		id:'mystore/storexfxq',
		name:'getStorexfxq'
	},									
	getsyylist:{//获取营业员列表 
		id:'mystore/getsyyxlist',
		name:'getsyylist'
	},          
	bdsyy:{//绑定营业员  
		id:'mystore/bdsyy',
		name:'getBdsyy'
	},            
	deletesyy:{//删除营业员 
		id:'mystore/deletesyy',
		name:'getDeletesyy'
	},              
	editsyy:{//编辑营业员权限	
		id:'mystore/editsyy',
		name:'get'
	},	
	yyyskewm:{//营业员收款二维码	
		id:'scores/yyyskewm',
		name:'getYyyskewm'
	},									
	AddCoupons:{//添加优惠券
		id:'mystore/AddCoupons',
		name:'getAddCoupons'
	},					
	couponsList:{//优惠券列表	
		id:'mystore/CouponsList',
		name:'getCouponsList'
	},	
    clipCouponsList:{//个人的优惠券列表
		id:'mymember/ClipCouponsList',
		name:'getClipCouponsList'
	},  						
	reback:{//账单明细退款	
		id:'mystore/reback',
		name:'getReback'
	},			
	zzlist:{//店铺申请赞助的列表
		id:'zz/zzlist',
		name:'getZzlist'
	},			
	editstorepic:{//店铺店铺的主图或者幻灯图片
		id:'mymember/editstorepic',
		name:'getEditstorepic'
	},         
	editlogo:{//编辑店铺图片logo	
		id:'mymember/editlogo',
		name:'getEditlogo'
	},				
	edit:{//编辑店铺内容	
		id:'mymember/edit',
		name:'getEdit'
	},
	myzz:{//我的赞助	
		id:'mymember/myzzx',
		name:'getMyzz'
	},							
	cashOut:{//消费提现	
		id:'mystore/CashOut',
		name:'getCashOut'
	},			
	resetsms:{//开启短信提醒	
		id:'menber/resetsms',
		name:'getResetsms'
	},
	storeagree:{//转商家协议
		id:'news/storeagree',
		name:'getStoreagree'
	},
	storexxje:{//消费记录列表(月份)
		id:'mystore/xxstorexxje',
		name:'getStorexxje'
	},
	getshoptxlist:{//消费提现列表（月份）
		id:'mystore/getshoptxlist',
		name:'getshoptxlist'
	}
}

export default ary